CREATE INDEX "alerts_created_at_idx" ON "alerts" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "alerts_read_idx" ON "alerts" USING btree ("read");--> statement-breakpoint
CREATE INDEX "alerts_acknowledged_idx" ON "alerts" USING btree ("acknowledged");--> statement-breakpoint
CREATE INDEX "alerts_severity_idx" ON "alerts" USING btree ("severity");--> statement-breakpoint
CREATE INDEX "alerts_investigation_id_idx" ON "alerts" USING btree ("investigationId");--> statement-breakpoint
CREATE INDEX "alerts_subject_ref_idx" ON "alerts" USING btree ("subjectRef");--> statement-breakpoint
CREATE INDEX "aml_alerts_created_at_idx" ON "aml_alerts" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "aml_alerts_status_idx" ON "aml_alerts" USING btree ("status");--> statement-breakpoint
CREATE INDEX "aml_alerts_rule_id_idx" ON "aml_alerts" USING btree ("ruleId");--> statement-breakpoint
CREATE INDEX "audit_log_created_at_idx" ON "audit_log" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "audit_log_user_id_idx" ON "audit_log" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "audit_log_category_idx" ON "audit_log" USING btree ("category");--> statement-breakpoint
CREATE INDEX "audit_log_target_ref_idx" ON "audit_log" USING btree ("targetRef");--> statement-breakpoint
CREATE INDEX "cases_status_idx" ON "cases" USING btree ("status");--> statement-breakpoint
CREATE INDEX "cases_created_at_idx" ON "cases" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "cases_lead_analyst_id_idx" ON "cases" USING btree ("leadAnalystId");--> statement-breakpoint
CREATE INDEX "cases_priority_idx" ON "cases" USING btree ("priority");--> statement-breakpoint
CREATE INDEX "duplicate_checks_status_idx" ON "duplicate_identity_checks" USING btree ("status");--> statement-breakpoint
CREATE INDEX "duplicate_checks_created_at_idx" ON "duplicate_identity_checks" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "field_agents_status_idx" ON "field_agents" USING btree ("status");--> statement-breakpoint
CREATE INDEX "field_agents_state_idx" ON "field_agents" USING btree ("state");--> statement-breakpoint
CREATE INDEX "field_agents_created_at_idx" ON "field_agents" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "field_tasks_status_idx" ON "field_tasks" USING btree ("status");--> statement-breakpoint
CREATE INDEX "field_tasks_created_at_idx" ON "field_tasks" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "field_tasks_investigation_id_idx" ON "field_tasks" USING btree ("investigationId");--> statement-breakpoint
CREATE INDEX "field_tasks_agent_id_idx" ON "field_tasks" USING btree ("agentId");--> statement-breakpoint
CREATE INDEX "field_tasks_priority_idx" ON "field_tasks" USING btree ("priority");--> statement-breakpoint
CREATE INDEX "goaml_filings_status_idx" ON "goaml_filings" USING btree ("status");--> statement-breakpoint
CREATE INDEX "goaml_filings_created_at_idx" ON "goaml_filings" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "hosted_links_status_idx" ON "hosted_verification_links" USING btree ("status");--> statement-breakpoint
CREATE INDEX "hosted_links_expires_at_idx" ON "hosted_verification_links" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "investigations_status_idx" ON "investigations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "investigations_created_at_idx" ON "investigations" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "investigations_updated_at_idx" ON "investigations" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX "investigations_assigned_to_idx" ON "investigations" USING btree ("assignedTo");--> statement-breakpoint
CREATE INDEX "investigations_created_by_idx" ON "investigations" USING btree ("createdBy");--> statement-breakpoint
CREATE INDEX "investigations_risk_score_idx" ON "investigations" USING btree ("riskScore");--> statement-breakpoint
CREATE INDEX "investigations_subject_name_idx" ON "investigations" USING btree ("subjectName");--> statement-breakpoint
CREATE INDEX "investigations_nin_idx" ON "investigations" USING btree ("nin");--> statement-breakpoint
CREATE INDEX "investigations_bvn_idx" ON "investigations" USING btree ("bvn");--> statement-breakpoint
CREATE INDEX "kyc_records_status_idx" ON "kyc_records" USING btree ("status");--> statement-breakpoint
CREATE INDEX "kyc_records_created_at_idx" ON "kyc_records" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "kyc_records_created_by_idx" ON "kyc_records" USING btree ("createdBy");--> statement-breakpoint
CREATE INDEX "kyc_records_investigation_id_idx" ON "kyc_records" USING btree ("investigationId");--> statement-breakpoint
CREATE INDEX "kyc_records_nin_idx" ON "kyc_records" USING btree ("nin");--> statement-breakpoint
CREATE INDEX "kyc_records_bvn_idx" ON "kyc_records" USING btree ("bvn");--> statement-breakpoint
CREATE INDEX "lex_submissions_status_idx" ON "lex_submissions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "lex_submissions_created_at_idx" ON "lex_submissions" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "lex_submissions_agency_id_idx" ON "lex_submissions" USING btree ("agencyId");--> statement-breakpoint
CREATE INDEX "monitors_status_idx" ON "monitors" USING btree ("status");--> statement-breakpoint
CREATE INDEX "monitors_created_at_idx" ON "monitors" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "monitors_created_by_idx" ON "monitors" USING btree ("createdBy");--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "notifications_read_idx" ON "notifications" USING btree ("read");--> statement-breakpoint
CREATE INDEX "notifications_created_at_idx" ON "notifications" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "onboarding_apps_status_idx" ON "onboarding_applications" USING btree ("status");--> statement-breakpoint
CREATE INDEX "onboarding_apps_created_at_idx" ON "onboarding_applications" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "onboarding_apps_created_by_idx" ON "onboarding_applications" USING btree ("createdBy");--> statement-breakpoint
CREATE INDEX "regulatory_reports_status_idx" ON "regulatory_reports" USING btree ("status");--> statement-breakpoint
CREATE INDEX "regulatory_reports_created_at_idx" ON "regulatory_reports" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "regulatory_reports_type_idx" ON "regulatory_reports" USING btree ("type");--> statement-breakpoint
CREATE INDEX "reports_status_idx" ON "reports" USING btree ("status");--> statement-breakpoint
CREATE INDEX "reports_created_at_idx" ON "reports" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "reports_generated_by_idx" ON "reports" USING btree ("generatedBy");--> statement-breakpoint
CREATE INDEX "reports_investigation_id_idx" ON "reports" USING btree ("investigationId");--> statement-breakpoint
CREATE INDEX "rule_evaluations_created_at_idx" ON "rule_evaluations" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "rule_evaluations_rule_id_idx" ON "rule_evaluations" USING btree ("ruleId");--> statement-breakpoint
CREATE INDEX "rule_evaluations_triggered_idx" ON "rule_evaluations" USING btree ("triggered");--> statement-breakpoint
CREATE INDEX "sar_filings_status_idx" ON "sar_filings" USING btree ("status");--> statement-breakpoint
CREATE INDEX "sar_filings_created_at_idx" ON "sar_filings" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "sar_filings_created_by_idx" ON "sar_filings" USING btree ("createdBy");--> statement-breakpoint
CREATE INDEX "screening_requests_status_idx" ON "screening_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "screening_requests_created_at_idx" ON "screening_requests" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "screening_requests_created_by_idx" ON "screening_requests" USING btree ("createdBy");--> statement-breakpoint
CREATE INDEX "social_mentions_created_at_idx" ON "social_mentions" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "social_mentions_monitor_id_idx" ON "social_mentions" USING btree ("monitorId");--> statement-breakpoint
CREATE INDEX "social_mentions_sentiment_idx" ON "social_mentions" USING btree ("sentiment");--> statement-breakpoint
CREATE INDEX "transactions_created_at_idx" ON "transactions" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "transactions_status_idx" ON "transactions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "transactions_originator_account_idx" ON "transactions" USING btree ("originatorAccount");--> statement-breakpoint
CREATE INDEX "transactions_amount_idx" ON "transactions" USING btree ("amount");--> statement-breakpoint
CREATE INDEX "user_sessions_user_id_idx" ON "user_sessions" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_sessions_expires_at_idx" ON "user_sessions" USING btree ("expiresAt");