CREATE TYPE "public"."spoof_type" AS ENUM('genuine', 'printed_photo', 'screen_replay', 'paper_mask', 'three_d_mask', 'deepfake', 'high_quality_photo', 'unknown');--> statement-breakpoint
CREATE TABLE "biometric_session_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar(64) NOT NULL,
	"subject_ref" varchar(128),
	"kyc_record_id" integer,
	"liveness_score" real,
	"liveness_live" boolean,
	"liveness_reason" varchar(128),
	"liveness_landmarks_found" boolean,
	"liveness_ear" real,
	"liveness_texture_score" real,
	"liveness_face_area_ratio" real,
	"liveness_landmark_variance" real,
	"active_liveness_score" real,
	"active_liveness_live" boolean,
	"active_liveness_challenge" varchar(32),
	"active_liveness_challenge_completed" boolean,
	"active_liveness_frames_analysed" integer,
	"face_detected" boolean,
	"face_count" integer,
	"face_quality_score" real,
	"face_bbox_x" real,
	"face_bbox_y" real,
	"face_bbox_w" real,
	"face_bbox_h" real,
	"landmarks_68" text,
	"embedding_dimension" integer,
	"embedding_model" varchar(64),
	"match_score" real,
	"match_cosine_similarity" real,
	"match_decision" boolean,
	"match_threshold" real,
	"anti_spoof_score" real,
	"anti_spoof_genuine" boolean,
	"anti_spoof_type" "spoof_type" DEFAULT 'unknown',
	"anti_spoof_model" varchar(64),
	"anti_spoof_sharpness" real,
	"anti_spoof_colour_depth" real,
	"anti_spoof_hf_score" real,
	"anti_spoof_freq_anomaly_score" real,
	"anti_spoof_reflection_score" real,
	"anti_spoof_depth_score" real,
	"overall_score" real,
	"overall_verified" boolean,
	"failure_reasons" text,
	"request_id" varchar(64),
	"latency_ms" real,
	"engine_version" varchar(32),
	"kafka_published" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "bio_session_subject_idx" ON "biometric_session_logs" USING btree ("subject_ref");--> statement-breakpoint
CREATE INDEX "bio_session_created_at_idx" ON "biometric_session_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "bio_session_spoof_type_idx" ON "biometric_session_logs" USING btree ("anti_spoof_type");--> statement-breakpoint
CREATE INDEX "bio_session_kyc_record_idx" ON "biometric_session_logs" USING btree ("kyc_record_id");