package main

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	_ "github.com/lib/pq"
)

const (
	outboxDispatchInterval = 2 * time.Second
	outboxBatchSize        = 50
	outboxMaxAttempts      = 12
)

type outboxEvent struct {
	ID             string
	Topic          string
	Payload        []byte
	AttemptCount   int
	IdempotencyKey string
}

type transactionalOutbox struct {
	db     *sql.DB
	cancel context.CancelFunc
	wg     sync.WaitGroup
}

var gatewayOutbox *transactionalOutbox

func newTransactionalOutbox(databaseURL string) (*transactionalOutbox, error) {
	if strings.TrimSpace(databaseURL) == "" {
		return nil, errors.New("DATABASE_URL is required for the gateway transactional outbox")
	}
	if !strings.HasPrefix(databaseURL, "postgres://") && !strings.HasPrefix(databaseURL, "postgresql://") {
		return nil, errors.New("gateway transactional outbox requires a PostgreSQL DATABASE_URL")
	}
	db, err := sql.Open("postgres", databaseURL)
	if err != nil {
		return nil, fmt.Errorf("open transactional outbox database: %w", err)
	}
	db.SetMaxOpenConns(12)
	db.SetMaxIdleConns(6)
	db.SetConnMaxLifetime(30 * time.Minute)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("ping transactional outbox database: %w", err)
	}
	return &transactionalOutbox{db: db}, nil
}

func (o *transactionalOutbox) close() error {
	if o == nil {
		return nil
	}
	if o.cancel != nil {
		o.cancel()
	}
	o.wg.Wait()
	return o.db.Close()
}

func stableEventKey(topic string, payload []byte) string {
	var decoded map[string]any
	if json.Unmarshal(payload, &decoded) == nil {
		for _, key := range []string{"event_id", "eventId", "reference", "request_id", "requestId", "transfer_id", "transferId"} {
			if value, ok := decoded[key]; ok && strings.TrimSpace(fmt.Sprint(value)) != "" {
				return fmt.Sprintf("%s:%s", topic, strings.TrimSpace(fmt.Sprint(value)))
			}
		}
	}
	// Events without a domain reference remain individually durable. The UUID is
	// generated by a cryptographically secure source in github.com/google/uuid.
	return fmt.Sprintf("%s:%s", topic, uuid.NewString())
}

func (o *transactionalOutbox) enqueue(topic string, payload any) error {
	if o == nil || o.db == nil {
		return errors.New("gateway transactional outbox is unavailable")
	}
	if strings.TrimSpace(topic) == "" {
		return errors.New("outbox topic is required")
	}
	encoded, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal outbox payload for %s: %w", topic, err)
	}
	hash := sha256.Sum256(encoded)
	idempotencyKey := stableEventKey(topic, encoded)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_, err = o.db.ExecContext(ctx, `
		INSERT INTO gateway_transactional_outbox
		  (id, topic, payload, payload_sha256, idempotency_key, state, available_at)
		VALUES ($1, $2, $3::jsonb, $4, $5, 'pending', NOW())
		ON CONFLICT (topic, idempotency_key) DO NOTHING`,
		uuid.NewString(), topic, string(encoded), hex.EncodeToString(hash[:]), idempotencyKey)
	if err != nil {
		controlPlaneMetrics.outboxEvents.WithLabelValues("persistence_error").Inc()
		return fmt.Errorf("persist durable event %s: %w", topic, err)
	}
	controlPlaneMetrics.outboxEvents.WithLabelValues("persisted").Inc()
	return nil
}

func (o *transactionalOutbox) start() {
	if o == nil || o.db == nil || o.cancel != nil {
		return
	}
	ctx, cancel := context.WithCancel(context.Background())
	o.cancel = cancel
	o.wg.Add(1)
	go func() {
		defer o.wg.Done()
		ticker := time.NewTicker(outboxDispatchInterval)
		defer ticker.Stop()
		for {
			if err := o.dispatchPending(ctx); err != nil && !errors.Is(err, context.Canceled) {
				log.Printf("[OUTBOX] dispatch cycle failed: %v", err)
			}
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
			}
		}
	}()
	log.Printf("[OUTBOX] PostgreSQL transactional dispatcher started")
}

func (o *transactionalOutbox) dispatchPending(ctx context.Context) error {
	if kafkaProducer == nil {
		return nil
	}
	tx, err := o.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin outbox lease transaction: %w", err)
	}
	rows, err := tx.QueryContext(ctx, `
		SELECT id, topic, payload::text, attempt_count, idempotency_key
		FROM gateway_transactional_outbox
		WHERE state = 'pending' AND available_at <= NOW()
		ORDER BY available_at ASC, created_at ASC
		FOR UPDATE SKIP LOCKED
		LIMIT $1`, outboxBatchSize)
	if err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("select pending outbox events: %w", err)
	}
	events := make([]outboxEvent, 0, outboxBatchSize)
	for rows.Next() {
		var event outboxEvent
		var payload string
		if err := rows.Scan(&event.ID, &event.Topic, &payload, &event.AttemptCount, &event.IdempotencyKey); err != nil {
			_ = rows.Close()
			_ = tx.Rollback()
			return fmt.Errorf("scan outbox event: %w", err)
		}
		event.Payload = []byte(payload)
		events = append(events, event)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		_ = tx.Rollback()
		return fmt.Errorf("iterate outbox events: %w", err)
	}
	_ = rows.Close()
	for _, event := range events {
		if _, err := tx.ExecContext(ctx, `UPDATE gateway_transactional_outbox SET state = 'dispatching', updated_at = NOW() WHERE id = $1`, event.ID); err != nil {
			_ = tx.Rollback()
			return fmt.Errorf("lease outbox event: %w", err)
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit outbox lease: %w", err)
	}

	for _, event := range events {
		if err := kafkaProducer.Publish(event.Topic, event.Payload); err != nil {
			if markErr := o.markFailed(ctx, event, err); markErr != nil {
				return markErr
			}
			continue
		}
		if _, err := o.db.ExecContext(ctx, `
			UPDATE gateway_transactional_outbox
			SET state = 'delivered', delivered_at = NOW(), updated_at = NOW(), last_error = NULL
			WHERE id = $1 AND state = 'dispatching'`, event.ID); err != nil {
			return fmt.Errorf("mark delivered outbox event %s: %w", event.ID, err)
		}
		controlPlaneMetrics.outboxEvents.WithLabelValues("delivered").Inc()
	}
	var pending float64
	if err := o.db.QueryRowContext(ctx, `SELECT COUNT(*) FROM gateway_transactional_outbox WHERE state = 'pending'`).Scan(&pending); err == nil {
		controlPlaneMetrics.outboxBacklog.Set(pending)
	}
	return nil
}

func (o *transactionalOutbox) markFailed(ctx context.Context, event outboxEvent, publishErr error) error {
	nextAttempt := event.AttemptCount + 1
	state := "pending"
	if nextAttempt >= outboxMaxAttempts {
		state = "dead_letter"
	}
	backoff := time.Duration(1<<min(nextAttempt, 8)) * time.Second
	if _, err := o.db.ExecContext(ctx, `
		UPDATE gateway_transactional_outbox
		SET state = $2, attempt_count = $3, last_error = $4,
			available_at = CASE WHEN $2 = 'pending' THEN NOW() + $5::interval ELSE available_at END,
			updated_at = NOW()
		WHERE id = $1`, event.ID, state, nextAttempt, truncateOutboxError(publishErr), fmt.Sprintf("%f seconds", backoff.Seconds())); err != nil {
		return fmt.Errorf("mark failed outbox event %s: %w", event.ID, err)
	}
	controlPlaneMetrics.outboxEvents.WithLabelValues(state).Inc()
	return nil
}

func truncateOutboxError(err error) string {
	message := err.Error()
	if len(message) > 2_000 {
		return message[:2_000]
	}
	return message
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func initializeTransactionalOutbox() error {
	outbox, err := newTransactionalOutbox(os.Getenv("DATABASE_URL"))
	if err != nil {
		return err
	}
	gatewayOutbox = outbox
	controlPlaneMetrics.setDependencyHealth("postgres_outbox", true)
	gatewayOutbox.start()
	return nil
}
