import { createHmac, randomUUID } from "node:crypto";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { ENV } from "./_core/env";
import { getPgPool } from "./db";
import { protectedProcedure, router, writeProcedure } from "./_core/trpc";
import { encryptPiiEnvelope, loadPiiEnvelopeKeyring, piiAad } from "./piiEnvelopeCrypto";

const CASE_REF = /^BIS-AA-[A-Z0-9]{18}$/;
const FCRA_MIN_WAIT_DAYS = 5;

function ref(): string { return `BIS-AA-${randomUUID().replace(/-/g, "").slice(0, 18).toUpperCase()}`; }
function tenant(ctx: { tenantId: number | null }): number { if (ctx.tenantId === null) throw new TRPCError({ code: "FORBIDDEN", message: "Tenant context is required." }); return ctx.tenantId; }
async function pool() { const value = await getPgPool(); if (!value) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "PostgreSQL is unavailable." }); return value; }
function eventHash(input: Record<string, unknown>): string { if (!ENV.auditHmacSecret) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "Audit integrity key is unavailable." }); return createHmac("sha256", ENV.auditHmacSecret).update(JSON.stringify(input)).digest("hex"); }
function roleProcedure(kind: "adjudicator" | "admin") {
  return writeProcedure.use(async ({ ctx, next }) => {
    if (!ctx.user || (kind === "admin" ? ctx.user.role !== "admin" : !["admin", "supervisor", "analyst"].includes(ctx.user.role))) {
      throw new TRPCError({ code: "FORBIDDEN", message: kind === "admin" ? "Administrator role required." : "Designated adjudicator role required." });
    }
    return next({ ctx });
  });
}
const adjudicatorProcedure = roleProcedure("adjudicator");
const administratorProcedure = roleProcedure("admin");
const caseRefSchema = z.string().regex(CASE_REF);

async function appendEvent(client: import("pg").PoolClient, adverseActionCaseId: string, actorUserId: number, eventType: string, detail: Record<string, unknown>) {
  const createdAt = new Date().toISOString();
  await client.query(`INSERT INTO compliance_adverse_action_events (adverse_action_case_id, actor_user_id, event_type, detail, integrity_hash, created_at) VALUES ($1,$2,$3,$4::jsonb,$5,$6::timestamptz)`, [adverseActionCaseId, actorUserId, eventType, JSON.stringify(detail), eventHash({ adverseActionCaseId, actorUserId, eventType, detail, createdAt }), createdAt]);
}
async function lockedCase(client: import("pg").PoolClient, caseRef: string, tenantId: number) {
  const query = await client.query<{ id: string; status: string; candidate_id: number; screening_order_id: number; final_notice_eligible_at: string | null }>(`SELECT id,status,candidate_id,screening_order_id,final_notice_eligible_at FROM compliance_adverse_action_cases WHERE case_ref=$1 AND tenant_id=$2 FOR UPDATE`, [caseRef, tenantId]);
  if (!query.rows[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Adverse-action case not found." });
  return query.rows[0];
}
async function assertNoOpenDispute(client: import("pg").PoolClient, candidateId: number, tenantId: number) {
  const open = await client.query(`SELECT 1 FROM consumer_dispute_cases cds JOIN consumer_subject_bindings csb ON csb.id=cds.subject_binding_id WHERE csb.candidate_id=$1 AND cds.tenant_id=$2 AND cds.status NOT IN ('completed','withdrawn','closed') LIMIT 1`, [candidateId, tenantId]);
  if (open.rowCount) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "A consumer dispute is open; adverse action must remain paused." });
}

export const complianceWorkflowRouter = router({
  createNoticeTemplate: administratorProcedure.input(z.object({ templateKey: z.enum(["pre_adverse","final_adverse","undeliverable","dispute_hold","dispute_result"]), jurisdictionCode: z.string().trim().min(2).max(16), version: z.string().trim().min(1).max(32), body: z.string().trim().min(32).max(100_000) })).mutation(async ({ ctx, input }) => {
    const tenantId = tenant(ctx); const keyring = loadPiiEnvelopeKeyring(); const encrypted = encryptPiiEnvelope(keyring, `bis-compliance-template:v1|${tenantId}|${input.templateKey}|${input.jurisdictionCode}|${input.version}`, { body: input.body }); const db = await pool();
    const inserted = await db.query<{ id: string }>(`INSERT INTO compliance_notice_templates (tenant_id,template_key,jurisdiction_code,version,body_ciphertext,body_nonce,body_key_version,content_sha256,approved_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`, [tenantId,input.templateKey,input.jurisdictionCode,input.version,encrypted.ciphertext,encrypted.nonce,encrypted.keyVersion,encrypted.plaintextSha256,ctx.user.id]);
    return { templateId: inserted.rows[0]!.id, version: input.version };
  }),

  initiatePreAdverse: adjudicatorProcedure.input(z.object({ screeningOrderId: z.number().int().positive(), reportSnapshotId: z.number().int().positive(), jurisdictionCode: z.string().trim().min(2).max(16), waitingPeriodDays: z.number().int().min(FCRA_MIN_WAIT_DAYS).max(30), templateVersion: z.string().trim().min(1).max(32), items: z.array(z.object({ screeningResultId: z.number().int().positive(), rationale: z.string().trim().min(20).max(4_000) })).min(1).max(50), employerAttestation: z.string().trim().min(40).max(4_000) })).mutation(async ({ ctx, input }) => {
    const tenantId = tenant(ctx); if (input.jurisdictionCode === "US" && process.env.BIS_FCRA_ADVERSE_ACTION_ENABLED !== "true") throw new TRPCError({ code: "FORBIDDEN", message: "FCRA adverse action is not counsel-approved and enabled for this environment." });
    const db = await pool(); const client = await db.connect();
    try { await client.query("BEGIN");
      const source = await client.query<{ candidate_id: number }>(`SELECT so."candidateId" AS candidate_id FROM screening_orders so JOIN consumer_report_snapshots rs ON rs.id=$2 AND rs.tenant_id=$1 AND rs.screening_order_id=so.id AND rs.candidate_id=so."candidateId" WHERE so.id=$3 AND so."tenantId"=$1 FOR UPDATE`, [tenantId,input.reportSnapshotId,input.screeningOrderId]);
      if (!source.rows[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Order and immutable report snapshot must belong to this tenant and candidate." });
      await assertNoOpenDispute(client, source.rows[0].candidate_id, tenantId);
      const template = await client.query<{ id: string }>(`SELECT id FROM compliance_notice_templates WHERE tenant_id=$1 AND template_key='pre_adverse' AND jurisdiction_code=$2 AND version=$3 AND superseded_at IS NULL`, [tenantId,input.jurisdictionCode,input.templateVersion]);
      if (!template.rows[0]) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Counsel-approved pre-adverse template is unavailable." });
      const caseRef = ref(); const inserted = await client.query<{ id: string }>(`INSERT INTO compliance_adverse_action_cases (case_ref,tenant_id,screening_order_id,candidate_id,report_snapshot_id,jurisdiction_code,status,waiting_period_days,initiated_by,employer_attestation_at,employer_attestation_text) VALUES ($1,$2,$3,$4,$5,$6,'pre_notice_queued',$7,$8,NOW(),$9) RETURNING id`, [caseRef,tenantId,input.screeningOrderId,source.rows[0].candidate_id,input.reportSnapshotId,input.jurisdictionCode,input.waitingPeriodDays,ctx.user.id,input.employerAttestation]);
      const keyring = loadPiiEnvelopeKeyring(); for (const item of input.items) { const result = await client.query(`SELECT 1 FROM screening_results WHERE id=$1 AND "orderId"=$2 FOR UPDATE`, [item.screeningResultId,input.screeningOrderId]); if (!result.rowCount) throw new TRPCError({ code: "BAD_REQUEST", message: "Selected adverse-action item is not in this screening order." }); const encrypted = encryptPiiEnvelope(keyring, piiAad(tenantId,"candidate_profile",source.rows[0].candidate_id,`adverse-rationale:${caseRef}:${item.screeningResultId}`), { rationale:item.rationale }); await client.query(`INSERT INTO compliance_adverse_action_items (adverse_action_case_id,screening_result_id,rationale_ciphertext,rationale_nonce,rationale_key_version) VALUES ($1,$2,$3,$4,$5)`, [inserted.rows[0]!.id,item.screeningResultId,encrypted.ciphertext,encrypted.nonce,encrypted.keyVersion]); }
      const contentHash = eventHash({ caseRef, type:"pre_adverse", templateVersion:input.templateVersion, itemCount:input.items.length }); await client.query(`INSERT INTO compliance_notice_deliveries (adverse_action_case_id,template_id,notice_type,channel,status,content_sha256) VALUES ($1,$2,'pre_adverse','portal','queued',$3)`, [inserted.rows[0]!.id,template.rows[0]!.id,contentHash]); await appendEvent(client,inserted.rows[0]!.id,ctx.user.id,"created",{ caseRef, itemCount:input.items.length, jurisdiction:input.jurisdictionCode }); await appendEvent(client,inserted.rows[0]!.id,ctx.user.id,"pre_notice_queued",{ templateVersion:input.templateVersion }); await client.query("COMMIT"); return { caseRef, status:"pre_notice_queued" as const };
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }),

  recordDelivery: adjudicatorProcedure.input(z.object({ caseRef: caseRefSchema, deliveryId: z.string().uuid(), status: z.enum(["delivered","undeliverable","manual_required"]), providerMessageRef: z.string().trim().min(4).max(256).optional() })).mutation(async ({ctx,input}) => { const tenantId=tenant(ctx); const db=await pool(); const client=await db.connect(); try { await client.query("BEGIN"); const c=await lockedCase(client,input.caseRef,tenantId); const delivery=await client.query<{notice_type:string}>(`SELECT nd.notice_type FROM compliance_notice_deliveries nd WHERE nd.id=$1 AND nd.adverse_action_case_id=$2 AND nd.status='queued' FOR UPDATE`,[input.deliveryId,c.id]); if(!delivery.rows[0]) throw new TRPCError({code:"PRECONDITION_FAILED",message:"Queued notice delivery not found."}); if(input.status==="delivered" && delivery.rows[0].notice_type==="pre_adverse"){ await client.query(`UPDATE compliance_notice_deliveries SET status='delivered',sent_at=NOW(),delivered_at=NOW(),provider_message_ref=$1 WHERE id=$2`,[input.providerMessageRef??null,input.deliveryId]); await client.query(`UPDATE compliance_adverse_action_cases SET status='waiting',pre_notice_due_at=NOW(),final_notice_eligible_at=NOW()+make_interval(days=>waiting_period_days),updated_at=NOW() WHERE id=$1`,[c.id]); await appendEvent(client,c.id,ctx.user.id,"pre_notice_delivered",{deliveryId:input.deliveryId}); } else { await client.query(`UPDATE compliance_notice_deliveries SET status=$1,provider_message_ref=$2 WHERE id=$3`,[input.status,input.providerMessageRef??null,input.deliveryId]); await client.query(`UPDATE compliance_adverse_action_cases SET status=$1,updated_at=NOW() WHERE id=$2`,[input.status==="undeliverable"?"undeliverable":"manual_delivery",c.id]); await appendEvent(client,c.id,ctx.user.id,"manual_delivery_required",{deliveryId:input.deliveryId,status:input.status}); } await client.query("COMMIT"); return {caseRef:input.caseRef,status:input.status}; } catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();} }),

  pauseForDispute: adjudicatorProcedure.input(z.object({caseRef:caseRefSchema, disputeCaseRef:z.string().regex(/^BIS-DR-[A-Z0-9]{18}$/)})).mutation(async({ctx,input})=>{const tenantId=tenant(ctx);const db=await pool();const client=await db.connect();try{await client.query("BEGIN");const c=await lockedCase(client,input.caseRef,tenantId);const disputed=await client.query(`SELECT 1 FROM consumer_dispute_cases WHERE case_ref=$1 AND tenant_id=$2 AND status NOT IN ('completed','withdrawn','closed')`,[input.disputeCaseRef,tenantId]);if(!disputed.rowCount)throw new TRPCError({code:"PRECONDITION_FAILED",message:"An open tenant-scoped dispute is required to pause adverse action."});await client.query(`UPDATE compliance_adverse_action_cases SET status='paused_for_dispute',updated_at=NOW() WHERE id=$1 AND status IN ('waiting','pre_notice_delivered')`,[c.id]);await appendEvent(client,c.id,ctx.user.id,"paused_for_dispute",{disputeCaseRef:input.disputeCaseRef});await client.query("COMMIT");return{caseRef:input.caseRef,status:"paused_for_dispute" as const};}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}),

  queueFinalAdverse: adjudicatorProcedure.input(z.object({caseRef:caseRefSchema,templateVersion:z.string().trim().min(1).max(32)})).mutation(async({ctx,input})=>{const tenantId=tenant(ctx);const db=await pool();const client=await db.connect();try{await client.query("BEGIN");const c=await lockedCase(client,input.caseRef,tenantId);if(c.status!=="waiting"||!c.final_notice_eligible_at||new Date(c.final_notice_eligible_at)>new Date())throw new TRPCError({code:"PRECONDITION_FAILED",message:"Pre-adverse waiting period has not completed."});await assertNoOpenDispute(client,c.candidate_id,tenantId);const template=await client.query<{id:string}>(`SELECT id FROM compliance_notice_templates WHERE tenant_id=$1 AND template_key='final_adverse' AND version=$2 AND superseded_at IS NULL`,[tenantId,input.templateVersion]);if(!template.rows[0])throw new TRPCError({code:"PRECONDITION_FAILED",message:"Counsel-approved final-adverse template is unavailable."});const digest=eventHash({caseRef:input.caseRef,type:"final_adverse",templateVersion:input.templateVersion});await client.query(`INSERT INTO compliance_notice_deliveries (adverse_action_case_id,template_id,notice_type,channel,status,content_sha256) VALUES($1,$2,'final_adverse','portal','queued',$3)`,[c.id,template.rows[0].id,digest]);await client.query(`UPDATE compliance_adverse_action_cases SET status='final_notice_queued',updated_at=NOW() WHERE id=$1`,[c.id]);await appendEvent(client,c.id,ctx.user.id,"final_notice_queued",{templateVersion:input.templateVersion});await client.query("COMMIT");return{caseRef:input.caseRef,status:"final_notice_queued" as const};}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}),

  cancel: adjudicatorProcedure.input(z.object({caseRef:caseRefSchema,reason:z.string().trim().min(20).max(4000)})).mutation(async({ctx,input})=>{const tenantId=tenant(ctx);const db=await pool();const client=await db.connect();try{await client.query("BEGIN");const c=await lockedCase(client,input.caseRef,tenantId);if(["completed","canceled"].includes(c.status))throw new TRPCError({code:"PRECONDITION_FAILED",message:"Completed or canceled adverse action cannot be changed."});await client.query(`UPDATE compliance_adverse_action_cases SET status='canceled',updated_at=NOW() WHERE id=$1`,[c.id]);await client.query(`UPDATE compliance_notice_deliveries SET status='canceled' WHERE adverse_action_case_id=$1 AND status='queued'`,[c.id]);await appendEvent(client,c.id,ctx.user.id,"canceled",{reason:input.reason});await client.query("COMMIT");return{caseRef:input.caseRef,status:"canceled" as const};}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}),

  list: protectedProcedure.input(z.object({status:z.string().optional()}).optional()).query(async({ctx,input})=>{const tenantId=tenant(ctx);const db=await pool();const res=await db.query(`SELECT case_ref,status,jurisdiction_code,waiting_period_days,final_notice_eligible_at,created_at FROM compliance_adverse_action_cases WHERE tenant_id=$1 AND ($2::text IS NULL OR status=$2) ORDER BY created_at DESC LIMIT 200`,[tenantId,input?.status??null]);return res.rows;}),
});
