#!/usr/bin/env python3
with open("server/routers.ts", "r", encoding="utf-8") as f:
    lines = f.readlines()

insert_before_idx = 2083
print(f"Inserting before line {insert_before_idx+1}: {repr(lines[insert_before_idx])}")

export_osint_procedure = '''
  /** Export a completed OSINT investigation as a PDF compliance report */
  exportOsintPdf: protectedProcedure
    .input(z.object({ id: z.number().int().positive() }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'DB unavailable' });
      const [record] = await db.select().from(screeningRequests).where(eq(screeningRequests.id, input.id)).limit(1);
      if (!record) throw new TRPCError({ code: 'NOT_FOUND', message: 'Investigation not found' });
      if (record.createdBy !== ctx.user.id) throw new TRPCError({ code: 'FORBIDDEN', message: 'Access denied' });
      const result = record.result as any;
      const osintReport: string = result?.osintReport ?? result?.resultText ?? 'No report content available.';
      const subjectName = record.subjectName ?? 'Unknown Subject';
      const requestRef = record.requestRef ?? `ID-${record.id}`;
      const riskScore = record.riskScore ?? 0;
      const completedAt = record.completedAt ?? record.createdAt ?? new Date();
      const riskColor = riskScore >= 80 ? '#e53e3e' : riskScore >= 60 ? '#dd6b20' : '#38a169';
      const riskLabel = riskScore >= 80 ? 'HIGH RISK' : riskScore >= 60 ? 'MEDIUM RISK' : 'LOW RISK';
      const mdToHtml = (md: string) => md
        .replace(/^## (.+)$/gm, '<h2>$1</h2>')
        .replace(/^### (.+)$/gm, '<h3>$1</h3>')
        .replace(/^# (.+)$/gm, '<h1>$1</h1>')
        .replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>')
        .replace(/\\*(.+?)\\*/g, '<em>$1</em>')
        .replace(/^- (.+)$/gm, '<li>$1</li>')
        .replace(/\\n\\n/g, '</p><p>');
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/>
<style>body{font-family:Arial,sans-serif;font-size:11pt;color:#1a202c;margin:0;padding:0}
.header{background:#1a365d;color:white;padding:24px 32px}.header h1{margin:0 0 4px;font-size:18pt}
.meta{display:flex;gap:24px;padding:16px 32px;background:#f7fafc;border-bottom:1px solid #e2e8f0}
.meta-item{flex:1}.meta-label{font-size:8pt;text-transform:uppercase;color:#718096}
.meta-value{font-size:11pt;font-weight:bold;color:#2d3748}
.risk-badge{display:inline-block;padding:4px 12px;border-radius:4px;font-weight:bold;font-size:10pt;color:white;background:${riskColor}}
.content{padding:24px 32px}h2{color:#1a365d;border-bottom:2px solid #bee3f8;padding-bottom:4px;margin-top:24px;font-size:13pt}
h3{color:#2c5282;font-size:11pt;margin-top:16px}ul{padding-left:20px}li{margin-bottom:4px}p{line-height:1.6}
.footer{border-top:1px solid #e2e8f0;padding:12px 32px;font-size:8pt;color:#718096;text-align:center}
@page{margin:15mm}</style></head><body>
<div class="header"><h1>Zero-Footprint OSINT Report</h1><p>BIS Platform &mdash; Confidential Compliance Document</p></div>
<div class="meta">
<div class="meta-item"><div class="meta-label">Subject</div><div class="meta-value">${escHtml(subjectName)}</div></div>
<div class="meta-item"><div class="meta-label">Reference</div><div class="meta-value">${escHtml(requestRef)}</div></div>
<div class="meta-item"><div class="meta-label">Completed</div><div class="meta-value">${new Date(completedAt).toLocaleDateString('en-NG')}</div></div>
<div class="meta-item"><div class="meta-label">Risk</div><div class="meta-value"><span class="risk-badge">${riskLabel} (${riskScore}/100)</span></div></div>
</div>
<div class="content"><p>${mdToHtml(osintReport)}</p></div>
<div class="footer">Generated by BIS Platform &bull; ${new Date().toISOString()} &bull; CONFIDENTIAL</div>
</body></html>`;
      const { execSync } = await import('child_process');
      const os = await import('os');
      const path = await import('path');
      const fs = await import('fs');
      const tmpDir = os.tmpdir();
      const htmlPath = path.join(tmpDir, `osint-${requestRef}.html`);
      const pdfPath = path.join(tmpDir, `osint-${requestRef}.pdf`);
      try {
        fs.writeFileSync(htmlPath, htmlContent, 'utf8');
        execSync(`weasyprint "${htmlPath}" "${pdfPath}"`, { timeout: 30000 });
        const pdfBuffer = fs.readFileSync(pdfPath);
        const fileKey = `osint-reports/${ctx.user.id}/${requestRef}-${Date.now()}.pdf`;
        const { url } = await storagePut(fileKey, pdfBuffer, 'application/pdf');
        fs.unlinkSync(htmlPath);
        fs.unlinkSync(pdfPath);
        return { url, filename: `OSINT-${requestRef}-${subjectName.replace(/[^a-zA-Z0-9]/g,'-')}.pdf` };
      } catch (err: any) {
        try { fs.unlinkSync(htmlPath); } catch {}
        try { fs.unlinkSync(pdfPath); } catch {}
        throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: `PDF generation failed: ${err?.message}` });
      }
    }),
'''

lines.insert(insert_before_idx, export_osint_procedure)
with open("server/routers.ts", "w", encoding="utf-8") as f:
    f.writelines(lines)
print(f"SUCCESS: exportOsintPdf inserted before line {insert_before_idx+1}")
