/**
 * UserProfileDashboard — User Profile & Session Status
 * =====================================================
 * Displays the authenticated user's profile, verified identity details,
 * current session status, and session refresh controls.
 */
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, Shield, Clock, User, CheckCircle2, XCircle, RefreshCw, Download, FileText } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

// ── Export Utilities ──────────────────────────────────────────────────────────

function escapeCSV(val: string): string {
  if (val.includes(",") || val.includes('"') || val.includes("\n")) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

function exportToCSV(records: any[]) {
  const headers = ["Date", "Type", "Subject", "Result", "Risk Score", "Verdict"];
  const rows = records.map((r: any) => [
    r.createdAt ? new Date(r.createdAt).toISOString() : "",
    r.type || "identity",
    r.subjectName || "",
    r.overallResult || "pending",
    r.riskScore != null ? String(r.riskScore) : "",
    r.verdict || "",
  ]);
  const csv = [headers.join(","), ...rows.map((row) => row.map(escapeCSV).join(","))].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `bis-verification-history-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
  toast.success("CSV exported successfully");
}

function exportToPDF(records: any[], userName: string) {
  // Generate a printable HTML document and trigger browser print dialog (PDF save)
  const rows = records.map((r: any) => `
    <tr>
      <td style="padding:6px;border:1px solid #ddd">${r.createdAt ? new Date(r.createdAt).toLocaleDateString() : "—"}</td>
      <td style="padding:6px;border:1px solid #ddd">${(r.type || "identity").toUpperCase()}</td>
      <td style="padding:6px;border:1px solid #ddd">${r.subjectName || "—"}</td>
      <td style="padding:6px;border:1px solid #ddd">${r.overallResult || "pending"}</td>
      <td style="padding:6px;border:1px solid #ddd">${r.riskScore != null ? r.riskScore : "—"}</td>
    </tr>
  `).join("");

  const html = `<!DOCTYPE html>
<html><head><title>BIS Verification Report</title>
<style>body{font-family:system-ui,sans-serif;padding:40px;max-width:800px;margin:0 auto}
h1{font-size:20px;color:#1a1a1a}table{width:100%;border-collapse:collapse;margin-top:20px}
th{background:#f5f5f5;padding:8px;border:1px solid #ddd;text-align:left;font-size:12px}
td{font-size:12px}.meta{color:#666;font-size:11px;margin-top:8px}</style></head>
<body>
<h1>BIS — Identity Verification Report</h1>
<p class="meta">Generated: ${new Date().toLocaleString()} | User: ${userName}</p>
<table><thead><tr><th>Date</th><th>Type</th><th>Subject</th><th>Result</th><th>Risk Score</th></tr></thead>
<tbody>${rows}</tbody></table>
<p class="meta" style="margin-top:24px">This report was generated by the BIS Background Intelligence System.
All verifications were performed against authoritative national databases via YouVerify.</p>
</body></html>`;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
    toast.success("PDF export opened — use your browser's Save as PDF option");
  } else {
    toast.error("Pop-up blocked — please allow pop-ups for PDF export");
  }
}

export default function UserProfileDashboard() {
  const { user, loading } = useAuth();
  const [refreshing, setRefreshing] = useState(false);

  // Fetch the user's KYC verification history
  const { data: kycHistory, isLoading: kycLoading } = trpc.quickcheck.history.useQuery(
    { limit: 5 },
    { enabled: !!user }
  );

  const handleRefreshSession = async () => {
    setRefreshing(true);
    try {
      // The refresh token is stored in the client's memory from the initial exchange
      // In production, this would call POST /api/auth/refresh with the stored refresh token
      const res = await fetch("/api/auth/refresh", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ refreshToken: localStorage.getItem("bis_refresh_token") || "" }),
        credentials: "include",
      });
      if (res.ok) {
        const data = await res.json();
        if (data.newRefreshToken) {
          localStorage.setItem("bis_refresh_token", data.newRefreshToken);
        }
        toast.success("Session refreshed successfully");
      } else {
        const err = await res.json().catch(() => ({ error: "Unknown error" }));
        toast.error(err.error || "Session refresh failed — please log in again");
      }
    } catch {
      toast.error("Network error — could not refresh session");
    } finally {
      setRefreshing(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="container max-w-2xl py-8">
        <Card>
          <CardContent className="pt-6 text-center">
            <XCircle className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-lg font-medium">Not Authenticated</p>
            <p className="text-muted-foreground mt-1">Please log in to view your profile.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="container max-w-3xl py-8 space-y-6">
      <h1 className="text-2xl font-bold">User Profile</h1>

      {/* Profile Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <User className="h-5 w-5" />
            {user.name || "Unknown User"}
          </CardTitle>
          <CardDescription>{user.email || "No email on file"}</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="text-muted-foreground">Role</span>
              <p className="font-medium capitalize">{user.role}</p>
            </div>
            <div>
              <span className="text-muted-foreground">Login Method</span>
              <p className="font-medium capitalize">{(user as any).loginMethod || "—"}</p>
            </div>
            <div>
              <span className="text-muted-foreground">User ID</span>
              <p className="font-mono text-xs">{(user as any).openId || user.id}</p>
            </div>
            <div>
              <span className="text-muted-foreground">Last Sign-In</span>
              <p className="font-medium">
                {(user as any).lastSignedIn
                  ? new Date((user as any).lastSignedIn).toLocaleString()
                  : "—"}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Session Status Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Clock className="h-5 w-5" />
            Session Status
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="h-2 w-2 rounded-full bg-green-500 animate-pulse" />
              <span className="text-sm font-medium">Active Session</span>
            </div>
            <Badge variant="outline" className="text-green-700 border-green-300">
              Authenticated
            </Badge>
          </div>
          <p className="text-xs text-muted-foreground">
            Sessions expire after 24 hours. Use the refresh button below to extend your session
            without logging in again.
          </p>
          <Button
            variant="outline"
            size="sm"
            onClick={handleRefreshSession}
            disabled={refreshing}
          >
            {refreshing ? (
              <Loader2 className="mr-2 h-3 w-3 animate-spin" />
            ) : (
              <RefreshCw className="mr-2 h-3 w-3" />
            )}
            Refresh Session
          </Button>
        </CardContent>
      </Card>

      {/* Verified Identity Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5" />
            Identity Verification History
          </CardTitle>
          <CardDescription>
            Results from NIN/BVN verifications performed on your account.
          </CardDescription>
          {kycHistory?.items && kycHistory.items.length > 0 && (
            <div className="flex gap-2 mt-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => exportToCSV(kycHistory.items)}
              >
                <Download className="mr-1.5 h-3 w-3" />
                CSV
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => exportToPDF(kycHistory.items, user.name || "Unknown")}
              >
                <FileText className="mr-1.5 h-3 w-3" />
                PDF
              </Button>
            </div>
          )}
        </CardHeader>
        <CardContent>
          {kycLoading ? (
            <div className="flex items-center gap-2 py-4">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span className="text-sm text-muted-foreground">Loading verification history...</span>
            </div>
          ) : kycHistory?.items && kycHistory.items.length > 0 ? (
            <div className="space-y-3">
              {kycHistory.items.map((record: any, i: number) => (
                <div key={i} className="flex items-center justify-between p-3 rounded-lg border">
                  <div className="flex items-center gap-3">
                    {record.overallResult === "clear" ? (
                      <CheckCircle2 className="h-5 w-5 text-green-600" />
                    ) : (
                      <XCircle className="h-5 w-5 text-red-600" />
                    )}
                    <div>
                      <p className="text-sm font-medium">{record.type?.toUpperCase() || "Identity Check"}</p>
                      <p className="text-xs text-muted-foreground">
                        {record.createdAt ? new Date(record.createdAt).toLocaleDateString() : "—"}
                      </p>
                    </div>
                  </div>
                  <Badge variant={record.overallResult === "clear" ? "default" : "destructive"}>
                    {record.overallResult || "pending"}
                  </Badge>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-6 text-muted-foreground">
              <Shield className="h-8 w-8 mx-auto mb-2 opacity-50" />
              <p className="text-sm">No verification records found.</p>
              <p className="text-xs mt-1">Complete a NIN or BVN verification to see results here.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
