/*!
 * insider_threat.rs — BIS Insider Threat Detection Module
 *
 * Provides behavioural anomaly detection for insider threat scenarios:
 *   - Unusual data access patterns (bulk access, off-hours, privilege escalation)
 *   - UEBA sliding-window scoring per subject
 *   - Alert generation for high-confidence anomalies
 *
 * The API is synchronous (non-async) to match the call site in main.rs.
 */

use axum::{extract::State, http::StatusCode, response::Json};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use tracing::{info, warn};

// ─── Types ────────────────────────────────────────────────────────────────────

/// An event descriptor passed from main.rs for insider threat analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventDescriptor {
    pub id: String,
    pub subject_id: String,
    pub subject_ref: String,
    pub payload_bytes: u64,
    pub occurred_at: chrono::DateTime<chrono::Utc>,
    pub is_privilege_change: bool,
}

/// An insider threat alert generated by the detector.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InsiderThreatAlert {
    pub alert_id: String,
    pub subject_id: String,
    pub subject_ref: String,
    pub risk_score: f64,
    pub indicators: Vec<String>,
    pub severity: String,
    pub description: String,
    pub timestamp: String,
}

/// Configuration for the insider threat detector.
#[derive(Debug, Clone)]
pub struct InsiderThreatConfig {
    /// Maximum events per subject before bulk-access alert fires.
    pub bulk_access_threshold: u64,
    /// Minimum payload bytes to consider a bulk export.
    pub bulk_export_bytes: u64,
    /// Off-hours window start (UTC hour, inclusive).
    pub off_hours_start: u32,
    /// Off-hours window end (UTC hour, exclusive).
    pub off_hours_end: u32,
    /// Maximum stored alerts before rotation.
    pub max_alerts: usize,
}

impl Default for InsiderThreatConfig {
    fn default() -> Self {
        Self {
            bulk_access_threshold: 100,
            bulk_export_bytes: 1_000_000,
            off_hours_start: 0,
            off_hours_end: 5,
            max_alerts: 200,
        }
    }
}

/// Shared state for the insider threat detector.
pub struct InsiderThreatDetector {
    config: InsiderThreatConfig,
    alerts: Mutex<Vec<InsiderThreatAlert>>,
    event_counts: Mutex<HashMap<String, u64>>,
    payload_totals: Mutex<HashMap<String, u64>>,
}

impl InsiderThreatDetector {
    /// Create a new detector with default configuration.
    pub fn with_default_config() -> Self {
        Self {
            config: InsiderThreatConfig::default(),
            alerts: Mutex::new(Vec::new()),
            event_counts: Mutex::new(HashMap::new()),
            payload_totals: Mutex::new(HashMap::new()),
        }
    }

    /// Analyse an event synchronously and return any triggered alerts.
    pub fn process(&self, event: &EventDescriptor) -> Vec<InsiderThreatAlert> {
        let mut triggered: Vec<InsiderThreatAlert> = Vec::new();

        // Update counters
        let event_count = {
            let mut counts = self.event_counts.lock().unwrap();
            let c = counts.entry(event.subject_id.clone()).or_insert(0);
            *c += 1;
            *c
        };
        let payload_total = {
            let mut totals = self.payload_totals.lock().unwrap();
            let t = totals.entry(event.subject_id.clone()).or_insert(0);
            *t += event.payload_bytes;
            *t
        };

        // Rule 1: Bulk access
        if event_count > self.config.bulk_access_threshold {
            triggered.push(InsiderThreatAlert {
                alert_id: format!("ITA-BULK-{}", nano_id()),
                subject_id: event.subject_id.clone(),
                subject_ref: event.subject_ref.clone(),
                risk_score: 75.0,
                indicators: vec!["bulk_access".to_string()],
                severity: "high".to_string(),
                description: format!(
                    "Subject {} has generated {} events — possible bulk data access",
                    event.subject_ref, event_count
                ),
                timestamp: chrono::Utc::now().to_rfc3339(),
            });
        }

        // Rule 2: Bulk export by payload size
        if payload_total > self.config.bulk_export_bytes {
            triggered.push(InsiderThreatAlert {
                alert_id: format!("ITA-EXPORT-{}", nano_id()),
                subject_id: event.subject_id.clone(),
                subject_ref: event.subject_ref.clone(),
                risk_score: 80.0,
                indicators: vec!["bulk_export".to_string()],
                severity: "high".to_string(),
                description: format!(
                    "Subject {} has transferred {} bytes — possible bulk data exfiltration",
                    event.subject_ref, payload_total
                ),
                timestamp: chrono::Utc::now().to_rfc3339(),
            });
        }

        // Rule 3: Privilege escalation
        if event.is_privilege_change {
            triggered.push(InsiderThreatAlert {
                alert_id: format!("ITA-PRIV-{}", nano_id()),
                subject_id: event.subject_id.clone(),
                subject_ref: event.subject_ref.clone(),
                risk_score: 85.0,
                indicators: vec!["privilege_escalation".to_string()],
                severity: "critical".to_string(),
                description: format!(
                    "Privilege change detected for subject {}",
                    event.subject_ref
                ),
                timestamp: chrono::Utc::now().to_rfc3339(),
            });
        }

        // Rule 4: Off-hours access
        let hour = event.occurred_at.hour();
        if hour >= self.config.off_hours_start && hour < self.config.off_hours_end {
            triggered.push(InsiderThreatAlert {
                alert_id: format!("ITA-OFFHRS-{}", nano_id()),
                subject_id: event.subject_id.clone(),
                subject_ref: event.subject_ref.clone(),
                risk_score: 45.0,
                indicators: vec!["off_hours_access".to_string()],
                severity: "medium".to_string(),
                description: format!(
                    "Off-hours access by subject {} at {:02}:00 UTC",
                    event.subject_ref, hour
                ),
                timestamp: chrono::Utc::now().to_rfc3339(),
            });
        }

        // Persist triggered alerts
        if !triggered.is_empty() {
            let mut stored = self.alerts.lock().unwrap();
            for alert in &triggered {
                info!(
                    "[InsiderThreat] Alert: subject={} severity={} score={:.0} indicators={:?}",
                    alert.subject_ref, alert.severity, alert.risk_score, alert.indicators
                );
                stored.push(alert.clone());
            }
            if stored.len() > self.config.max_alerts {
                stored.drain(0..50);
            }
        }

        triggered
    }

    /// Return the most recent `n` hours of alerts.
    pub fn recent_alerts(&self, hours: i64) -> Vec<InsiderThreatAlert> {
        let cutoff = chrono::Utc::now() - chrono::Duration::hours(hours);
        let stored = self.alerts.lock().unwrap();
        stored
            .iter()
            .filter(|a| {
                chrono::DateTime::parse_from_rfc3339(&a.timestamp)
                    .map(|t| t.with_timezone(&chrono::Utc) >= cutoff)
                    .unwrap_or(false)
            })
            .cloned()
            .collect()
    }
}

// ─── HTTP Handlers ────────────────────────────────────────────────────────────

/// Shared application state for Axum handlers.
pub type AppState = Arc<InsiderThreatDetector>;

/// POST /v1/insider/process-event — analyse an event for insider threats.
pub async fn handle_process_event(
    State(detector): State<AppState>,
    Json(event): Json<EventDescriptor>,
) -> (StatusCode, Json<serde_json::Value>) {
    let alerts = detector.process(&event);
    let count = alerts.len();
    info!("[InsiderThreat] Processed event: {} alert(s) triggered", count);
    (
        StatusCode::OK,
        Json(serde_json::json!({
            "alerts_triggered": count,
            "alerts": alerts,
        })),
    )
}

/// GET /v1/insider/alerts — list recent insider threat alerts (last 1 hour).
pub async fn handle_recent_alerts(
    State(detector): State<AppState>,
) -> (StatusCode, Json<serde_json::Value>) {
    let alerts = detector.recent_alerts(1);
    (
        StatusCode::OK,
        Json(serde_json::json!({
            "count": alerts.len(),
            "alerts": alerts,
        })),
    )
}

/// GET /v1/insider/user-profile — get event count profile for all subjects.
pub async fn handle_user_profile(
    State(detector): State<AppState>,
) -> (StatusCode, Json<serde_json::Value>) {
    let counts = detector.event_counts.lock().unwrap();
    (
        StatusCode::OK,
        Json(serde_json::json!({
            "profiles": *counts,
        })),
    )
}

/// POST /v1/insider/kafka-ingest — ingest a Kafka event for insider threat analysis.
pub async fn handle_kafka_ingest(
    State(detector): State<AppState>,
    Json(event): Json<EventDescriptor>,
) -> (StatusCode, Json<serde_json::Value>) {
    let alerts = detector.process(&event);
    (
        StatusCode::OK,
        Json(serde_json::json!({
            "ingested": true,
            "alerts_triggered": alerts.len(),
        })),
    )
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

fn nano_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    format!("{:08x}", nanos)
}

use chrono::Timelike;
