#!/usr/bin/env bash
# ============================================================================
# BIS LEX Intake Microservice — Field Deployment Installer
# ============================================================================
# Usage: sudo bash install.sh [OPTIONS]
#
# Options:
#   --bis-url URL       BIS platform URL (required)
#   --api-key KEY       BIS API key for sync (required)
#   --port PORT         HTTP port to listen on (default: 8090)
#   --sync-interval N   Sync interval in seconds (default: 300)
#   --uninstall         Remove the service and all data
#
# Requirements: Linux (Debian/Ubuntu/RHEL), systemd, internet access for install
# ============================================================================
set -euo pipefail

BINARY_URL="https://github.com/your-org/bis-pwa/releases/latest/download/lex-intake-linux-amd64"
SERVICE_USER="lexintake"
DATA_DIR="/var/lib/lex-intake"
CONFIG_DIR="/etc/lex-intake"
BINARY_PATH="/usr/local/bin/lex-intake"
SERVICE_FILE="/etc/systemd/system/lex-intake.service"

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "This script must be run as root (sudo bash install.sh)"

# ── Parse arguments ───────────────────────────────────────────────────────────
BIS_URL=""
API_KEY=""
PORT=8090
SYNC_INTERVAL=300
UNINSTALL=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --bis-url)        BIS_URL="$2";         shift 2 ;;
    --api-key)        API_KEY="$2";         shift 2 ;;
    --port)           PORT="$2";            shift 2 ;;
    --sync-interval)  SYNC_INTERVAL="$2";   shift 2 ;;
    --uninstall)      UNINSTALL=true;       shift ;;
    *) error "Unknown option: $1" ;;
  esac
done

# ── Uninstall path ────────────────────────────────────────────────────────────
if $UNINSTALL; then
  info "Stopping and removing lex-intake service..."
  systemctl stop lex-intake  2>/dev/null || true
  systemctl disable lex-intake 2>/dev/null || true
  rm -f "$SERVICE_FILE" "$BINARY_PATH"
  systemctl daemon-reload
  warn "Data directory $DATA_DIR was NOT removed. Remove manually if desired: rm -rf $DATA_DIR"
  info "Uninstall complete."
  exit 0
fi

# ── Validate required args ────────────────────────────────────────────────────
[[ -z "$BIS_URL" ]] && error "Missing --bis-url. Example: --bis-url https://bis.yourorg.com"
[[ -z "$API_KEY" ]] && error "Missing --api-key. Obtain from BIS Admin > API Tokens."

# ── Detect architecture ───────────────────────────────────────────────────────
ARCH=$(uname -m)
case $ARCH in
  x86_64)  ARCH_SUFFIX="linux-amd64" ;;
  aarch64) ARCH_SUFFIX="linux-arm64" ;;
  armv7l)  ARCH_SUFFIX="linux-armv7" ;;
  *)       error "Unsupported architecture: $ARCH" ;;
esac
BINARY_URL="https://github.com/your-org/bis-pwa/releases/latest/download/lex-intake-${ARCH_SUFFIX}"

# ── Create service user ───────────────────────────────────────────────────────
if ! id "$SERVICE_USER" &>/dev/null; then
  info "Creating service user: $SERVICE_USER"
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi

# ── Create directories ────────────────────────────────────────────────────────
info "Creating data and config directories..."
mkdir -p "$DATA_DIR" "$CONFIG_DIR"
chown "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR"
chmod 750 "$DATA_DIR" "$CONFIG_DIR"

# ── Download binary ───────────────────────────────────────────────────────────
info "Downloading lex-intake binary (${ARCH_SUFFIX})..."
if command -v curl &>/dev/null; then
  curl -fsSL "$BINARY_URL" -o "$BINARY_PATH"
elif command -v wget &>/dev/null; then
  wget -q "$BINARY_URL" -O "$BINARY_PATH"
else
  error "Neither curl nor wget found. Install one and retry."
fi
chmod 755 "$BINARY_PATH"
info "Binary installed at $BINARY_PATH"

# ── Write environment file ────────────────────────────────────────────────────
info "Writing configuration to $CONFIG_DIR/env..."
cat > "$CONFIG_DIR/env" <<EOF
# BIS LEX Intake — Environment Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change settings, then: sudo systemctl restart lex-intake

LEX_PORT=${PORT}
LEX_DB_PATH=${DATA_DIR}/lex_offline.db
LEX_BIS_API_URL=${BIS_URL}
LEX_BIS_API_KEY=${API_KEY}
LEX_SYNC_INTERVAL=${SYNC_INTERVAL}
LEX_MAX_QUEUE_SIZE=10000
EOF
chmod 640 "$CONFIG_DIR/env"
chown root:"$SERVICE_USER" "$CONFIG_DIR/env"

# ── Install systemd service ───────────────────────────────────────────────────
info "Installing systemd service..."
cat > "$SERVICE_FILE" <<'UNIT'
[Unit]
Description=BIS LEX Intake Microservice
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
User=lexintake
Group=lexintake
ExecStart=/usr/local/bin/lex-intake
Restart=always
RestartSec=5
EnvironmentFile=-/etc/lex-intake/env
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/lex-intake
PrivateTmp=true
PrivateDevices=true
LimitNOFILE=65536
MemoryMax=256M
StandardOutput=journal
StandardError=journal
SyslogIdentifier=lex-intake

[Install]
WantedBy=multi-user.target
UNIT

# ── Enable and start ──────────────────────────────────────────────────────────
systemctl daemon-reload
systemctl enable lex-intake
systemctl restart lex-intake

# ── Verify ────────────────────────────────────────────────────────────────────
sleep 2
if systemctl is-active --quiet lex-intake; then
  info "✓ lex-intake is running on port ${PORT}"
  info "  Health check: curl http://localhost:${PORT}/health"
  info "  Logs: journalctl -u lex-intake -f"
  info "  Config: $CONFIG_DIR/env"
  info "  Data: $DATA_DIR/lex_offline.db"
else
  error "Service failed to start. Check logs: journalctl -u lex-intake -n 50"
fi

echo ""
info "Installation complete. Officers can now submit to http://$(hostname -I | awk '{print $1}'):${PORT}/submit"
